@baseUrl = http://localhost:3000

# RECADOS
## Lista todos os recados
GET {{baseUrl}}/recados/?limit=10&offset=0

// ?limit=15&offset=10 são parametros de query

### Lista apenas um recado
GET {{baseUrl}}/recados/-1
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Criação aleatoria de recados",
    "deId": 14,
    "paraId": 10
    }
### Atualiza um recado
PATCH {{baseUrl}}/recados/15/
Content-Type: application/json

{
    "texto": "De leo para pablo",
    "lido": false
}

### Essa rota apaga um recado
DELETE {{baseUrl}}/recados/1/

###

# PESSOAS
## Lista todos os pessoas
GET {{baseUrl}}/pessoas/?limit=10&offset=10 

// ?limit=15&offset=10 são parametros de query

### Lista apenas um pessoa
GET {{baseUrl}}/pessoas/2
### Cria um recado
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "leo@gmail.com",
    "password": "9984884",
    "nome": "Leo"
}

### Atualiza um pessoa
PATCH {{baseUrl}}/pessoas/9/
Content-Type: application/json

{
    "password": "871554",
    "nome": "Luiz"
}

### Essa rota apaga um pessoa
DELETE {{baseUrl}}/pessoas/12/


###