@baseUrl = http://localhost:3000

# RECADOS
## Lista todos os recados
GET {{baseUrl}}/recados/?limit=15&offset=10 

// ?limit=15&offset=10 são parametros de query

### Lista apenas um recado
GET {{baseUrl}}/recados/3
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Ana Ca",
    "de": "45516565",
    "para": "João",
    "bla": "dsfjjsdj"
}
### Atualiza um recado
PATCH {{baseUrl}}/recados/3/
Content-Type: application/json

{
    "texto": "akdas",
    "lido": true,
    "HASHDA": 23
}

### Essa rota apaga um recado
DELETE {{baseUrl}}/recados/2